package pcd.poool.model.collision.resolver;

import pcd.poool.model.ball.Ball;
import pcd.poool.model.ball.BallPair;
import pcd.poool.model.collision.util.CollisionAccumulator;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Multithreaded collision resolver based on a map-reduce pipeline.
 *
 * <p>Candidate pairs are first generated by the uniform-grid broad phase.
 * The map phase is parallel: each worker thread processes a strided subset of
 * candidate indexes and writes only to its private accumulator map.
 * The reduce/apply phase is shared with the task-based resolver.
 */
public class ThreadedCollisionResolver extends AbstractMapReduceCollisionResolver {

    private final int threadCount;

    /**
     * Creates a resolver with the provided number of worker threads.
     *
     * @param threadCount number of worker threads (must be greater than zero)
     */
    public ThreadedCollisionResolver(int threadCount) {
        this(threadCount, 0.02);
    }

    /**
     * Creates a resolver with explicit worker count and broad-phase cell size.
     *
     * @param threadCount number of worker threads (must be greater than zero)
     * @param cellSize uniform-grid cell size used by the broad phase
     */
    public ThreadedCollisionResolver(int threadCount, double cellSize) {
        super(cellSize);
        if (threadCount <= 0) {
            throw new IllegalArgumentException("threadCount must be > 0");
        }
        this.threadCount = threadCount;
    }

    /**
     * Resolves collisions among small balls using parallel map and serial reduce phases.
     *
     * @param balls mutable list of small balls
     * @throws InterruptedException if the current thread is interrupted while joining workers
     */
    @Override
    protected List<Map<Ball, CollisionAccumulator>> computeAccumulatorMaps(List<Ball> balls, List<BallPair> candidates)
            throws InterruptedException {
        List<Map<Ball, CollisionAccumulator>> accMaps = new ArrayList<>(threadCount);
        List<Thread> threads = new ArrayList<>(threadCount);

        for (int t = 0; t < threadCount; t++) {
            final int tid = t;
            final Map<Ball, CollisionAccumulator> localMap = new HashMap<>();
            accMaps.add(localMap);

            threads.add(new Thread(() -> super.processStridedCandidates(tid, threadCount, candidates, balls, localMap)));
        }

        for (Thread th : threads) th.start();
        for (Thread th : threads) th.join();

        return accMaps;
    }

    /**
     * Resolves big-ball collisions in parallel by partitioning small balls across worker threads.
     *
     * <p>Each thread writes only to its local accumulator map and local set of impacted
     * small balls. A serial reduce/apply then updates both the big ball and all small balls
     * once, preserving map-reduce semantics.</p>
     *
     * @param bigBall big ball involved in collisions
     * @param hitter hitter attribution to assign to impacted small balls
     * @param smallBalls mutable list of small balls
     * @throws InterruptedException if interrupted while waiting for workers
     */
    @Override
    public void resolveBigBallCollisions(Ball bigBall, Ball.HitBy hitter, List<Ball> smallBalls)
            throws InterruptedException {
        if (super.validateBigBallInputs(hitter, smallBalls)) {
            return;
        }

        List<Map<Ball, CollisionAccumulator>> accMaps = new ArrayList<>(threadCount);
        List<Set<Ball>> hitSets = new ArrayList<>(threadCount);
        List<Thread> threads = new ArrayList<>(threadCount);

        for (int t = 0; t < threadCount; t++) {
            final int tid = t;
            final Map<Ball, CollisionAccumulator> localMap = new HashMap<>();
            final Set<Ball> localHits = new HashSet<>();
            accMaps.add(localMap);
            hitSets.add(localHits);

            threads.add(new Thread(() -> super.processStridedBigBallCandidates(
                    tid,
                    threadCount,
                    bigBall,
                    smallBalls,
                    localMap,
                    localHits
            )));
        }

        for (Thread thread : threads) {
            thread.start();
        }
        for (Thread thread : threads) {
            thread.join();
        }

        super.applyBigBallResults(bigBall, hitter, smallBalls, accMaps, hitSets);
    }
}
