package pcd.poool.model.collision.resolver;

import pcd.poool.model.ball.Ball;
import pcd.poool.model.ball.BallPair;
import pcd.poool.model.collision.util.CollisionAccumulator;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Multithreaded collision resolver based on a map-reduce pipeline.
 *
 * <p>Candidate pairs are first generated by a {@link UniformGridBroadPhase}.
 * The map phase is parallel: each worker thread processes a strided subset of
 * candidate indexes and writes only to its private accumulator map.
 * The reduce/apply phase is shared with the task-based resolver.
 */
public class ThreadedCollisionResolver extends AbstractMapReduceCollisionResolver {

    private final int threadCount;

    /**
     * Creates a resolver with the provided number of worker threads.
     *
     * @param threadCount number of worker threads (must be greater than zero)
     */
    public ThreadedCollisionResolver(int threadCount) {
        this(threadCount, 0.02);
    }

    /**
     * Creates a resolver with explicit worker count and broad-phase cell size.
     *
     * @param threadCount number of worker threads (must be greater than zero)
     * @param cellSize uniform-grid cell size used by the broad phase
     */
    public ThreadedCollisionResolver(int threadCount, double cellSize) {
        super(cellSize);
        if (threadCount <= 0) {
            throw new IllegalArgumentException("threadCount must be > 0");
        }
        this.threadCount = threadCount;
    }

    /**
     * Resolves collisions among small balls using parallel map and serial reduce phases.
     *
     * @param balls mutable list of small balls
     * @throws InterruptedException if the current thread is interrupted while joining workers
     */
    @Override
    protected List<Map<Ball, CollisionAccumulator>> computeAccumulatorMaps(List<Ball> balls, List<BallPair> candidates)
            throws InterruptedException {
        List<Map<Ball, CollisionAccumulator>> accMaps = new ArrayList<>(threadCount);
        List<Thread> threads = new ArrayList<>(threadCount);

        for (int t = 0; t < threadCount; t++) {
            final int tid = t;
            final Map<Ball, CollisionAccumulator> localMap = new HashMap<>();
            accMaps.add(localMap);

            threads.add(new Thread(() -> processStridedCandidates(tid, threadCount, candidates, balls, localMap)));
        }

        for (Thread th : threads) th.start();
        for (Thread th : threads) th.join();

        return accMaps;
    }
}
