package pcd.poool.model.collision.resolver;

import pcd.poool.model.ball.Ball;
import pcd.poool.model.ball.BallCollision;
import pcd.poool.model.collision.util.BallPair;
import pcd.poool.model.collision.util.CollisionAccumulator;
import pcd.poool.model.collision.util.UniformGridBroadPhase;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Multithreaded collision resolver based on a map-reduce pipeline.
 *
 * <p>Candidate pairs are first generated by a {@link UniformGridBroadPhase}.
 * The map phase is parallel: each worker thread processes a strided subset of
 * candidate indexes and writes only to its private accumulator map.
 * The reduce phase is serial and merges all per-thread deltas before applying
 * them once per ball.
 */
public class ThreadedCollisionResolver implements CollisionResolver {

    private static final double DEFAULT_CELL_SIZE = 0.02;

    private final int threadCount;
    private final UniformGridBroadPhase broadPhase;

    /**
     * Creates a resolver with the provided number of worker threads.
     *
     * @param threadCount number of worker threads (must be greater than zero)
     */
    public ThreadedCollisionResolver(int threadCount) {
        this(threadCount, DEFAULT_CELL_SIZE);
    }

    /**
     * Creates a resolver with explicit worker count and broad-phase cell size.
     *
     * @param threadCount number of worker threads (must be greater than zero)
     * @param cellSize uniform-grid cell size used by the broad phase
     */
    public ThreadedCollisionResolver(int threadCount, double cellSize) {
        if (threadCount <= 0) {
            throw new IllegalArgumentException("threadCount must be > 0");
        }
        this.threadCount = threadCount;
        this.broadPhase = new UniformGridBroadPhase(cellSize);
    }

    /**
     * Resolves collisions among small balls using parallel map and serial reduce phases.
     *
     * @param balls mutable list of small balls
     * @throws InterruptedException if the current thread is interrupted while joining workers
     */
    @Override
    public void resolve(List<Ball> balls) throws InterruptedException {
        List<BallPair> candidates = broadPhase.computeCandidates(balls);
        int m = candidates.size();
        if (m == 0) return;

        List<Map<Ball, CollisionAccumulator>> accMaps = new ArrayList<>(threadCount);
        List<Thread> threads = new ArrayList<>(threadCount);

        for (int t = 0; t < threadCount; t++) {
            final int tid = t;
            final Map<Ball, CollisionAccumulator> localMap = new HashMap<>();
            accMaps.add(localMap);

            threads.add(new Thread(() -> {
                for (int k = tid; k < m; k += threadCount) {
                    BallPair pair = candidates.get(k);
                    Ball a = balls.get(pair.i());
                    Ball b = balls.get(pair.j());
                    CollisionAccumulator accA = localMap.computeIfAbsent(a, ignored -> new CollisionAccumulator());
                    CollisionAccumulator accB = localMap.computeIfAbsent(b, ignored -> new CollisionAccumulator());
                    BallCollision.resolveAccumulator(a, b, accA, accB);
                }
            }));
        }

        for (Thread th : threads) th.start();
        for (Thread th : threads) th.join();

        for (Ball ball : balls) {
            double dx = 0, dy = 0, dvx = 0, dvy = 0;
            for (Map<Ball, CollisionAccumulator> map : accMaps) {
                CollisionAccumulator acc = map.get(ball);
                if (acc != null) {
                    dx += acc.getDx();
                    dy += acc.getDy();
                    dvx += acc.getDvx();
                    dvy += acc.getDvy();
                }
            }
            if (dx != 0 || dy != 0 || dvx != 0 || dvy != 0) {
                CollisionAccumulator merged = new CollisionAccumulator();
                merged.add(dx, dy, dvx, dvy);
                BallCollision.applyAccumulator(ball, merged);
            }
        }
    }
}
