package pcd.poool.jpf;

import pcd.poool.model.ball.Ball;
import pcd.poool.model.collision.resolver.ThreadedCollisionResolver;
import pcd.poool.model.collision.resolver.UniformGridSerialCollisionResolver;
import pcd.poool.model.collision.util.UniformGridBroadPhase;
import pcd.poool.util.P2d;
import pcd.poool.util.V2d;

import java.util.ArrayList;
import java.util.List;

public class TestThreadedCollisionResolver {
    private static final double CELL_SIZE = 0.12;

    public static void main(String[] args) throws InterruptedException {
        List<Ball> initial = initBallsPositions();
        List<Ball> serialResult = copyBalls(initial);
        List<Ball> threadedResult = copyBalls(initial);
        
        int candidateCount = new UniformGridBroadPhase(CELL_SIZE).computeCandidates(initial).size();
        if (candidateCount == 0) {
            throw new AssertionError("JPF Test FAILED: No collision candidates generated by broad-phase. " +
                    "This prevents JPF from exploring concurrent scheduling. Candidates returned: " + candidateCount);
        }
        System.out.println("[JPF] Candidate pairs for scheduling: " + candidateCount);

        new UniformGridSerialCollisionResolver(CELL_SIZE).resolve(serialResult);

        new ThreadedCollisionResolver(2, CELL_SIZE).resolve(threadedResult);

        verifyStateIsFinite(threadedResult);
    }

    private static List<Ball> initBallsPositions() {
        List<Ball> balls = new ArrayList<>();
        balls.add(new Ball(new P2d(0.40, 0.50), 0.05, 1.0, new V2d(0.12, 0.00)));
        balls.add(new Ball(new P2d(0.47, 0.50), 0.05, 1.0, new V2d(0.00, 0.00)));
        balls.add(new Ball(new P2d(0.54, 0.50), 0.05, 1.0, new V2d(-0.02, 0.00)));
        balls.add(new Ball(new P2d(0.61, 0.50), 0.05, 1.0, new V2d(0.00, 0.01)));
        return balls;
    }

    private static List<Ball> copyBalls(List<Ball> source) {
        List<Ball> copy = new ArrayList<>(source.size());
        for (Ball ball : source) {
            Ball cloned = new Ball(
                    new P2d(ball.getPos().x(), ball.getPos().y()),
                    ball.getRadius(),
                    ball.getMass(),
                    new V2d(ball.getVel().x(), ball.getVel().y())
            );
            cloned.setLastHitBy(ball.getLastHitBy());
            copy.add(cloned);
        }
        return copy;
    }

    private static void verifyStateIsFinite(List<Ball> balls) {
        if (balls.size() != 4) {
            throw new AssertionError("Unexpected ball count: " + balls.size());
        }
        for (Ball ball : balls) {
            if (!Double.isFinite(ball.getPos().x()) || !Double.isFinite(ball.getPos().y())) {
                throw new AssertionError("Non-finite position detected");
            }
            if (!Double.isFinite(ball.getVel().x()) || !Double.isFinite(ball.getVel().y())) {
                throw new AssertionError("Non-finite velocity detected");
            }
        }
    }
}
